// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://skawgxuhhmcsxhvecdav.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNrYXdneHVoaG1jc3hodmVjZGF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAwNTEwNzgsImV4cCI6MjA1NTYyNzA3OH0.4_Vs6aHxsBAp08lF-ogpgCwP7_5HNF36zSNid_Jv59k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);